rib/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from rib import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('service.urls')),
    path('user/', include('user.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path, include
from service.views import *


app_name = 'service'

urlpatterns = [
    path('', ServicesList.as_view(), name='services_list'),
    path('service/info/<int:pk>/', ServiceInfo.as_view(), name='service_info'),
    path('service/save-data/', SaveData.as_view(), name='save_data'),
    path('service/step-by-step/<int:pk>/', StepByStep.as_view(), name='step_by_step'),
    path('service/save-data-succes/', SaveDataSuccess.as_view(), name='save_data_success'),
    path('applications/list/', ApplicationsList.as_view(), name='applications_list'),
    path('application/detail/<int:pk>', ApplicationDetail.as_view(), name='application_detail'),
    path('get-car-data/', GetCarData.as_view(), name='get_car_data'),
]

user/urls.py
from django.urls import path, include
from user.views import *


app_name = 'user'

urlpatterns = [
    # path('', ServicesList.as_view(), name='services_list'),
    path('login/', login_first, name='login_first'),
    path('is-register/', is_register, name='is_register'),
    path('signup/', user_signup, name='signup'),
    path('forgot-pass/', forgot_pass, name='forgot_pass'),
    path('logout/', user_logout, name='logout'),
    path('custom-logout/', Logout.as_view(), name='custom_logout'),

    #ajax
    path('get-district/', get_district, name='get_district'),
    path('get_quarter/', get_quarter, name='get_quarter'),
    path('get-code/', get_code, name='get_code'),

    path('save-user-information/', Save_User_Information.as_view(), name='save_user_information'),
    path('save-passport-data/', save_passport_data.as_view(), name='save_passport_data'),

]

templates/_parts/header-navbar.html
{% load static %}
{% load i18n %}
<div class="navbar-custom">
    <div class="container-fluid">
        <ul class="list-unstyled topnav-menu float-end mb-0">
            <li class="dropdown d-inline-block d-lg-none">
                <a class="nav-link dropdown-toggle arrow-none waves-effect waves-light" data-bs-toggle="dropdown"
                   href="#" role="button" aria-haspopup="false" aria-expanded="false">
                    <i class="fe-search noti-icon"></i>
                </a>
                <div class="dropdown-menu dropdown-lg dropdown-menu-end p-0">
                    <form class="p-3">
                        <input type="text" class="form-control" placeholder="Search ..."
                               aria-label="Recipient's username">
                    </form>
                </div>
            </li>
            <li class="dropdown d-none d-lg-inline-block">
                <a class="nav-link dropdown-toggle arrow-none waves-effect waves-light" data-toggle="fullscreen"
                   href="#">
                    <i class="fe-maximize noti-icon"></i>
                </a>
            </li>
            <li class="dropdown d-none d-lg-inline-block topbar-dropdown">
                <a class="nav-link dropdown-toggle arrow-none waves-effect waves-light" data-bs-toggle="dropdown"
                   href="#" role="button" aria-haspopup="false" aria-expanded="false">
                    <img src="{% static 'img/flags/en.png' %}" alt="user-image" height="16">
                </a>
                <div class="dropdown-menu dropdown-menu-end">
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item">
                        <img src="{% static 'img/flags/uz.png' %}" alt="user-image" class="me-1" height="12">
                        <span class="align-middle">O'zbekcha</span>
                    </a>
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item">
                        <img src="{% static 'img/flags/ru.png' %}" alt="user-image" class="me-1" height="12"> <span
                            class="align-middle">Русский</span>
                    </a>
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item">
                        <img src="{% static 'img/flags/en.png' %}" alt="user-image" class="me-1" height="12"> <span
                            class="align-middle">English</span>
                    </a>
                </div>
            </li>
            <li class="dropdown notification-list topbar-dropdown">
                <a class="nav-link dropdown-toggle waves-effect waves-light" data-bs-toggle="dropdown" href="#"
                   role="button" aria-haspopup="false" aria-expanded="false">
                    <i class="fe-bell noti-icon"></i>
                    <span class="badge bg-danger rounded-circle noti-icon-badge">9</span>
                </a>
                <div class="dropdown-menu dropdown-menu-end dropdown-lg">
                    <!-- item-->
                    <div class="dropdown-item noti-title">
                        <h5 class="m-0">
                                        <span class="float-end">
                                            <a href="" class="text-dark">
                                                <small>Clear All</small>
                                            </a>
                                        </span>Notification
                        </h5>
                    </div>
                    <div class="noti-scroll" data-simplebar>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item active">
                            <div class="notify-icon">
                                <img src="../assets/images/users/user-1.jpg" class="img-fluid rounded-circle"
                                     alt=""/></div>
                            <p class="notify-details">Cristina Pride</p>
                            <p class="text-muted mb-0 user-msg">
                                <small>Hi, How are you? What about our next meeting</small>
                            </p>
                        </a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-primary">
                                <i class="mdi mdi-comment-account-outline"></i>
                            </div>
                            <p class="notify-details">Caleb Flakelar commented on Admin
                                <small class="text-muted">1 min ago</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon">
                                <img src="../assets/images/users/user-4.jpg" class="img-fluid rounded-circle"
                                     alt=""/></div>
                            <p class="notify-details">Karen Robinson</p>
                            <p class="text-muted mb-0 user-msg">
                                <small>Wow ! this admin looks good and awesome design</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-warning">
                                <i class="mdi mdi-account-plus"></i>
                            </div>
                            <p class="notify-details">New user registered.
                                <small class="text-muted">5 hours ago</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-info">
                                <i class="mdi mdi-comment-account-outline"></i>
                            </div>
                            <p class="notify-details">Caleb Flakelar commented on Admin
                                <small class="text-muted">4 days ago</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-secondary">
                                <i class="mdi mdi-heart"></i>
                            </div>
                            <p class="notify-details">Carlos Crouch liked
                                <b>Admin</b>
                                <small class="text-muted">13 days ago</small>
                            </p>
                        </a>
                    </div>

                    <!-- All-->
                    <a href="javascript:void(0);"
                       class="dropdown-item text-center text-primary notify-item notify-all">
                        View all
                        <i class="fe-arrow-right"></i>
                    </a>

                </div>
            </li>

            <li class="dropdown notification-list topbar-dropdown">
                <a class="nav-link dropdown-toggle nav-user me-0 waves-effect waves-light" data-bs-toggle="dropdown"
                   href="#" role="button" aria-haspopup="false" aria-expanded="false">

                        <span class="pro-user-name ms-1">
                                    {{ request.user.first_name }} <i class="mdi mdi-chevron-down"></i>
                                </span>
                </a>
                <div class="dropdown-menu dropdown-menu-end profile-dropdown ">


                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="fe-user"></i>
                        <span>{% trans 'Mening profilim' %}</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="fe-settings"></i>
                        <span>{% trans "Sozlamalar" %}</span>
                    </a>

                    <div class="dropdown-divider"></div>

                    <!-- item-->
                    <a href="{% url 'user:logout' %}" class="dropdown-item notify-item">
                        <i class="fe-log-out"></i>
                        <span>{% trans "Tizimdan chiqish" %}</span>
                    </a>

                </div>
            </li>
        </ul>
        <!-- LOGO -->
        <div class="logo-box">

            <a href="{% url 'service:services_list' %}" class="logo logo-light text-center">
                            <span class="logo-sm">
                                <h5 class="text-light mt-3">E-RIB.UZ</h5>
                            </span>
                <span class="logo-lg">
                                <h2 class="text-light mt-3">E-RIB.UZ</h2>
                            </span>
            </a>
        </div>
        <ul class="list-unstyled topnav-menu topnav-menu-left m-0">
            <li>
                <button class="button-menu-mobile waves-effect waves-light">
                    <i class="fe-menu"></i>
                </button>
            </li>

            <li>
                <!-- Mobile menu toggle (Horizontal Layout)-->
                <a class="navbar-toggle nav-link" data-bs-toggle="collapse" data-bs-target="#topnav-menu-content">
                    <div class="lines">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </a>
                <!-- End mobile menu toggle-->
            </li>

            <li class="dropdown d-none d-xl-block">
                <a class="nav-link dropdown-toggle waves-effect waves-light" data-bs-toggle="dropdown" href="#"
                   role="button" aria-haspopup="false" aria-expanded="false">
                    Tizim haqida
                    <i class="mdi mdi-lightbulb-on-outline"></i>
                </a>
            </li>

            <li class="dropdown dropdown-mega d-none d-xl-block">
                <a class="nav-link dropdown-toggle waves-effect waves-light" data-bs-toggle="dropdown" href="#"
                   role="button" aria-haspopup="false" aria-expanded="false">
                    Qo'llanma
                    <i class="mdi mdi-file-document-multiple"></i>
                </a>

            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
</div>

templates/_parts/messages.html
{% if messages %}
    {% for message in messages %}
        {% if forloop.last %}
            <div class="alert alert-{% if message.tags == 'success' %}success{% else %}danger{% endif %}">
                <a class="close" href="" data-dismiss="alert">×</a>
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}
{% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}