rib/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from rib import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('service.urls')),
    path('user/', include('user.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path, include
from service.views import *


app_name = 'service'

urlpatterns = [
    path('', ServicesList.as_view(), name='services_list'),
    path('service/info/<int:pk>/', ServiceInfo.as_view(), name='service_info'),
    path('service/save-data/', SaveData.as_view(), name='save_data'),
    path('service/step-by-step/<int:pk>/', StepByStep.as_view(), name='step_by_step'),
    path('service/save-data-succes/', SaveDataSuccess.as_view(), name='save_data_success'),
    path('applications/list/', ApplicationsList.as_view(), name='applications_list'),
    path('application/detail/<int:pk>', ApplicationDetail.as_view(), name='application_detail'),
    path('get-car-data/', GetCarData.as_view(), name='get_car_data'),
]

user/urls.py
from django.urls import path, include
from user.views import *


app_name = 'user'

urlpatterns = [
    # path('', ServicesList.as_view(), name='services_list'),
    path('login/', login_first, name='login_first'),
    path('is-register/', is_register, name='is_register'),
    path('signup/', user_signup, name='signup'),
    path('forgot-pass/', forgot_pass, name='forgot_pass'),
    path('logout/', user_logout, name='logout'),
    path('custom-logout/', Logout.as_view(), name='custom_logout'),

    #ajax
    path('get-district/', get_district, name='get_district'),
    path('get_quarter/', get_quarter, name='get_quarter'),
    path('get-code/', get_code, name='get_code'),

    path('save-user-information/', Save_User_Information.as_view(), name='save_user_information'),
    path('save-passport-data/', save_passport_data.as_view(), name='save_passport_data'),

]

service/models.py
from django.db import models


# Create your models here.
from user.models import *



class Service(models.Model):
    service_id = models.IntegerField(verbose_name="Servis ID", unique=True)
    title = models.CharField(verbose_name="Xizmat nomi", max_length=255)
    desc = models.TextField()
    image = models.CharField(verbose_name="Foto", blank=True, max_length=255)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Xizmat'
        verbose_name_plural = 'Xizmatlar'


CREATED = 0 #Yaratildi
SHIPPED = 1  #Jo'natildi
ACCEPTED_FOR_CONSIDERATION = 2  # Ko'rib chiqish uchun qabul qilindi
WAITING_FOR_PAYMENT = 3
WAITING_FOR_ORIGINAL_DOCUMENTS = 4
SUCCESS = 5
REJECTED = 6


PROCESS_CHOICES = (
    (CREATED, "Ariza yaratildi"),
    (SHIPPED, "Jo'natildi"),
    (ACCEPTED_FOR_CONSIDERATION, "Ko'rib chiqish uchun qabul qilindi"),
    (WAITING_FOR_PAYMENT, "To'lovni kutmoqda"),
    (WAITING_FOR_ORIGINAL_DOCUMENTS, "Hujjatlarni asl nusxasini kutmoqda"),
    (SUCCESS, "Muvaffaqiyatli yakunlandi"),
    (REJECTED, "Rad etildi"),

)
CRON_CHOICES = (
    ('1', '3 days inside'),
    ('2', '7 days before'),
    ('3', '7 days after'),
)


class Application(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    created_user = models.ForeignKey(User, verbose_name='Yaratgan shaxs', on_delete=models.SET_NULL, null=True)
    created_date = models.DateTimeField(default=timezone.now, max_length=30)
    updated_date = models.DateTimeField(default=timezone.now, max_length=30)
    process = models.IntegerField(choices=PROCESS_CHOICES, max_length=10, verbose_name="Ariza holati", default=CREATED)
    is_payment = models.BooleanField("To\'lov qilingan", default=False)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, blank=True, null=True)
    password = models.IntegerField(blank=True, null=True, verbose_name='Ariza tekshiruv kodi')
    given_date = models.DateField('Berish sanasi', blank=True, null=True)
    given_time = models.CharField('Berish vaqti', max_length=10, blank=True, null=True)
    canceled_date = models.DateTimeField(max_length=30, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_block = models.BooleanField(default=True)
    cron = models.CharField(choices=CRON_CHOICES, max_length=15, verbose_name="CRON holati", default=1)
    department = models.ForeignKey(Department, verbose_name="Ariza topshirilgan IIB YHXB bo'limi",
                                   on_delete=models.CASCADE, blank=True, null=True,
                                   related_name='application_section')

    class Meta:
        verbose_name = 'Ariza'
        verbose_name_plural = 'Arizalar'
        ordering = ['-id']

    def __str__(self):
        return f"Application object: {self.id}"


NUMBER = 0
CHECKBOX = 1
TEXT = 2
TEXTAREA = 3
RADIO = 4
DATE = 5
DATE_TIME = 6
SELECT = 7
MANY_SELECT = 8

FIELD_TYPE_CHOICES = (
    (NUMBER, "number"),
    (CHECKBOX, "Checkbox"),
    (TEXT, "Text"),
    (TEXTAREA, "Textarea"),
    (RADIO, "Radio"),
    (DATE, "Date"),
    (DATE_TIME, "DateTime"),
    (SELECT, "Select"),
    (MANY_SELECT, "ManyToManySelect"),
)


class ServiceSelect(models.Model):
    slug = models.CharField(max_length=20)
    title = models.CharField(verbose_name="Nomi", max_length=255)  # Masalan Avtomobil nomi

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Forma uchun select"
        verbose_name_plural = "Forma uchun select"


class ServiceSelectItems(models.Model):
    service_select = models.ForeignKey(ServiceSelect, on_delete=models.CASCADE, related_name='service_select_items')
    value = models.CharField(verbose_name="Qiymati", unique=True, max_length=255)



    def __str__(self):
        return self.value

class ServiceInputField(models.Model):
    service = models.ManyToManyField(Service, verbose_name="Xizmatlar", related_name='service_input_field')
    # slug = models.CharField(verbose_name="Qo'llaniladigan nomi", max_length=20)
    title = models.CharField(verbose_name="Nomi", max_length=255)  # Masalan Davlat raqam belgisi
    field_name = models.CharField(verbose_name="Field nomi", max_length=225)
    placeholder = models.CharField(max_length=255, blank=True)
    field_type = models.IntegerField(verbose_name="Field turi", null=True, blank=True, choices=FIELD_TYPE_CHOICES)
    select = models.ForeignKey(ServiceSelect, on_delete=models.CASCADE, blank=True, null=True, related_name="select_input_field")
    max_length = models.IntegerField(verbose_name="Max Length", blank=True, null=True)
    sort = models.IntegerField(default=1)
    is_required = models.BooleanField(default=True)
    div_form_group = models.BooleanField(default=True)
    div_class = models.CharField(max_length=255, blank=True)
    css_class = models.CharField(max_length=255, blank=True)
    css_code = models.TextField(blank=True)
    js_code = models.TextField(blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Forma yaratish"
        verbose_name_plural = "Forma yaratishlar"
        ordering = ['sort']

class Document(models.Model):
    title = models.CharField(max_length=255, verbose_name='Hujjat nomi')

    def __str__(self):
        return self.title


class ServiceInfo(models.Model):
    service = models.ForeignKey(Service, verbose_name="Xizmat", on_delete=models.CASCADE, related_name='service_info')
    deadline = models.CharField(verbose_name="Muddati", max_length=20, )
    how_it_works = models.TextField()
    document = models.ManyToManyField(Document, related_name='service_documents')

    def __str__(self):
        return self.service.title


class ServiceDataSave(models.Model):
    # application = models.ForeignKey(Application, on_delete=models.CASCADE, )
    field = models.TextField()
    data = models.TextField()


class SaveDataForm(models.Model):
    items = models.ForeignKey(ServiceInputField, on_delete=models.CASCADE)
    data = models.CharField(max_length=255)
    application = models.ForeignKey(Application, verbose_name='Application', on_delete=models.CASCADE, related_name='save_from_data_with_application')


class StepByStep(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='step_by_step_with_service')

    def __str__(self):
        return f"StepByStep: {self.service.title}"


class Step(models.Model):
    step_by_step = models.ForeignKey(StepByStep, on_delete=models.CASCADE, related_name='step_with_step_by_step')
    input_fields = models.ManyToManyField(ServiceInputField, related_name='step_with_service_fields', blank=True)
    title = models.CharField(max_length=255)
    sort = models.IntegerField(blank=True, null=True)
    css_id = models.CharField(max_length=255, blank=True)
    icon = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return f"Steps: {self.title}"

    class Meta:
        ordering = ['sort']

USER_TYPE = 0
FORM = 1
PAYMENT_FOR_APP = 2
PAYMENT_STATE_DUTY = 3

ELEMENT_TYPE_CHOICES = (
    (USER_TYPE, "USER_TYPE"),
    (FORM, "FORM"),
    (PAYMENT_FOR_APP, "PAYMENT_FOR_APP"),
    (PAYMENT_STATE_DUTY, "PAYMENT_STATE_DUTY"),

)


class StepElement(models.Model):
    step = models.ForeignKey(Step, on_delete=models.CASCADE, related_name='step_elements')
    type_element = models.IntegerField(verbose_name="Element turi", choices=ELEMENT_TYPE_CHOICES)

service/views.py
import datetime

import requests
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
# @login_required
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView

from rib.settings import MINIMUM_BASE_WAGE
from service.mixins import ApplicationCustomMixin, AllowedRolesMixin
from service.models import *


class ServicesList(ListView):
    model = Service
    template_name = 'rib/services/services_list.html'
    ordering = ['id']

    context_object_name = 'services'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_queryset(self):
        qs = super().get_queryset().filter(is_active=True)
        return qs


class ServiceInfo(DetailView):
    model = Service
    template_name = 'rib/services/service_info.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context.update(form_fields=ServiceInputField.objects.filter(service=self.kwargs.get('pk')))
        context.update(NUMBER=NUMBER)
        context.update(CHECKBOX=CHECKBOX)
        context.update(TEXT=TEXT)
        context.update(TEXTAREA=TEXTAREA)
        context.update(RADIO=RADIO)
        context.update(DATE=DATE)
        context.update(DATE_TIME=DATE_TIME)
        context.update(SELECT=SELECT)

        return context


class SaveData(View):
    def post(self, request, *args, **kwargs):
        service = Service.objects.get(pk=request.POST.get('service'))
        application = Application.objects.create(created_user=request.user, service=service)
        print(request.POST)

        for key, values in request.POST.lists():
            # print(key, ': ', values)
            if key != 'csrfmiddlewaretoken' and key != 'service':
                if key == 'person_type' and values == ['1']:
                    organization = Organization.objects.get(pk=request.POST.get('organization'))
                    Application.objects.filter(pk=application.pk).update(organization=organization)
                try:
                    item = ServiceInputField.objects.filter(field_name=key).first()
                except ServiceInputField.DoesNotExist:
                    item = None
                if key != 'person_type' and key != 'organization':
                    # print(key, 67)
                    is_many_select = ServiceInputField.objects.filter(field_name=key).first()
                    # print(is_many_select, 69)
                    if is_many_select.field_type == MANY_SELECT and item is not None:

                        for value in values:
                            # get_item = ServiceSelectItems.objects.filter(id=value).first()

                            save_data = SaveDataForm.objects.create(items=is_many_select, data=value,
                                                                    application=application)
                    else:
                        values = str(values).replace("[", "").replace("]", "").replace("'", "")
                        save_data = SaveDataForm.objects.create(items=item, data=values, application=application)

        return redirect(reverse_lazy('service:save_data_success'))


class SaveDataSuccess(LoginRequiredMixin, View):
    template_name = 'rib/services/save_form_success.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class StepByStep(LoginRequiredMixin, DetailView):
    model = StepByStep
    template_name = 'rib/services/step_by_step.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(USER_TYPE=USER_TYPE)
        context.update(FORM=FORM)
        context.update(PAYMENT_STATE_DUTY=PAYMENT_STATE_DUTY)
        context.update(PAYMENT_FOR_APP=PAYMENT_FOR_APP)
        context.update(NUMBER=NUMBER)
        context.update(CHECKBOX=CHECKBOX)
        context.update(TEXT=TEXT)
        context.update(TEXTAREA=TEXTAREA)
        context.update(RADIO=RADIO)
        context.update(DATE=DATE)
        context.update(DATE_TIME=DATE_TIME)
        context.update(SELECT=SELECT)
        context.update(MANY_SELECT=MANY_SELECT)
        return context


class ApplicationsList(AllowedRolesMixin, ApplicationCustomMixin):
    model = Application
    template_name = 'rib/application/applications_list.html'
    allowed_roles = [USER, REVIEWER, CHECKER, TECHNICAL, DISTRICAL_CONTROLLER, REGIONAL_CONTROLLER, STATE_CONTROLLER,
                     OPERATOR, MODERATOR, ADMINISTRATOR, SUPER_ADMINISTRATOR]
    render_application_values = ['id', 'service', 'created_user', 'created_date', 'process']

    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            return self.get_json_data()
        else:
            return super().get(self, request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = {
            'saved_datas': list(),
            'application_list': self.object_list
        }
        for application in self.get_queryset():

            saved_datas = SaveDataForm.objects.filter(application=application)
            if saved_datas.exists():
                context['saved_datas'].append(saved_datas)
                context['saved_datas'].append(application.process)
        return context


class ApplicationDetail(DetailView):
    model = Application
    template_name = 'rib/application/application_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        steps = Step.objects.filter(step_by_step__service__application__pk=self.kwargs.get('pk'))
        context.update(steps=steps)
        made_year = SaveDataForm.objects.get(application_id=self.kwargs.get('pk'), items__field_name='made_year')
        this_time = datetime.datetime.now()
        age = this_time.year - int(made_year.data)

        context.update(age=age)
        context.update(MINIMUM_BASE_WAGE=MINIMUM_BASE_WAGE)
        return context


class GetCarData(View):
    def post(self, request, *args, **kwargs):
        return HttpResponse(self.get_context_data(), content_type='json')

    def get_context_data(self):
        context = dict()
        application = Application.objects.filter(id=self.request.POST.get('app_id')).first()
        save_data = SaveDataForm.objects.filter(application=application, items__field_name='car_model').first()
        if save_data:
            car = ServiceInputField.objects.filter(id=save_data.items.id).first()
            print(car)

        else:
            pass

        return context

templates/rib/services/save_form_success.html
{% extends 'base.html' %}
{% block top %}
    <meta http-equiv="refresh" content="5; URL={% url  'service:applications_list'  %}"/>
{% endblock top %}
{% block content %}
    <h1 class="text-capitalize text-center text-success">Tabriklaymiz!</h1>
    <h2 class="text-center ">Sizning ma'lumotlaringiz muvaffaqiyatli jo'natildi. Tez orada YHXB RIB xodimlari tomonidan
        sizga javob SMS xabarnomasi yetkaziladi.</h2>
    <h3 class="text-center ">5 soniyadan so'ng arizangiz xronologiyasini ko'rishingiz mumkin</h3>
    <center>
        <div class="spinner-border" style="width: 5rem; height: 5rem; margin: 0 auto;" role="status">
            <span class="sr-only">Iltimos kuting...</span>
        </div>
    </center>
{% endblock content %}

templates/rib/services/service_info.html
{% extends 'base_horizontal.html' %}
{% block top %}
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Secular+One&display=swap');

        .info_area {
        {#border: 1px solid #696969;#} background: #fff;
            border-radius: 15px;
            margin-top: 8px;
            padding-top: 10px;
            margin-bottom: 30px;
        }

        .title_service {
            font-family: Arial, Baskerville, monospace;
            color: #0D3349 !important;
        }

        .use_service {
            border: 1px solid black;
            background: #6c757d;
            border-radius: 0 19px 19px 0;

        }

        .use_service_text {
            font-size: 1.1rem;
            color: #fff;
            font-family: Arial, Baskerville, monospace;
            text-align: center;
            font-weight: bold;
        }

        .use_service_icon {
            display: flex;
            align-items: center;
            font-size: 1.5rem;
            color: #fff;
        }

        .link_service_use {
            display: block;
            border: 1px solid black;
            background: #6c757d;
        {#border-radius: 0 19px 19px 0;#} text-align: center;
            color: #fff;
            font-size: 1.2rem;
            padding: 10px;
            margin-bottom: 19px;
        }

        .link_service_use:hover {
            color: #fff;
        }
    </style>
{% endblock top %}
{#{% block page_title %}#}
{#    {{ service.title }}#}
{#{% endblock page_title %}#}

{% block content %}
    <div class="row">
        <div class="col-12 info_area">
            <h2 class="text-center m-1 text-blue title_service">{{ service.title }}</h2>
            <p class="text-justify font-15">{{ service.desc }}</p>
            {% for link in service.step_by_step_with_service.all %}
            <a href="{% url 'service:step_by_step' pk=link.pk %}" class="link_service_use  ">Boshlash</a>
         {% endfor %}
            {% for  service_info in service.service_info.all %}


                <div class="accordion" id="accordionPanelsStayOpenExample">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true"
                                    aria-controls="panelsStayOpen-collapseOne">
                                Bu qanday xizmat?
                            </button>
                        </h2>
                        <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show"
                             aria-labelledby="panelsStayOpen-headingOne">
                            <div class="accordion-body">
                                {{ service_info.how_it_works }}
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false"
                                    aria-controls="panelsStayOpen-collapseTwo">
                                Xizmat ko'rsatilishi muddati
                            </button>
                        </h2>
                        <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse"
                             aria-labelledby="panelsStayOpen-headingTwo">
                            <div class="accordion-body">
                                {{ service_info.deadline }} kun ichida
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="panelsStayOpen-headingThree">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false"
                                    aria-controls="panelsStayOpen-collapseThree">
                                Kerakli xujjatlar
                            </button>
                        </h2>
                        <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse"
                             aria-labelledby="panelsStayOpen-headingThree">
                            <div class="accordion-body">
                                <ul>

                                    {% for document in service_info.document.all %}
                                        <li>{{ document.title }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>


    </div>


{% endblock content %}

templates/rib/services/services_list.html
{% extends 'base_horizontal.html' %}

{% block top %}
    <style>
        .service_list:hover {
            -webkit-box-shadow: 0px 4px 15px 0px rgba(34, 60, 80, 0.2);
            -moz-box-shadow: 0px 4px 15px 0px rgba(34, 60, 80, 0.2);
            box-shadow: 0px 4px 15px 0px rgba(34, 60, 80, 0.2);
            transition: 0.5s;
            cursor: pointer;
        }

        .main-header {
            border-bottom: 1px solid #5f5f5f;
            padding: 5px;
            margin: 10px;
        }

        .content-page {
            padding-top: 5px !important;
        }

    </style>
{% endblock top %}
{% load static %}
{% block content %}
    {#<a href="{% url 'service:applications_list' %}">app</a>#}
    <div class="row">

        <div class="col-12 d-flex justify-content-center main-header">
            <div class="header text-center">
                <img src="{% static 'img/iiv.png' %}" alt="" width="100" height="100" class="m-2">
                <img src="{% static 'img/yhxb.png' %}" alt="" width="100" height="100" class="m-2">
                <h3>IIV  YXHB xizmatlari onlayn portaliga xush kelibsiz. Ortiqcha vaqt sarflamagan holda, IIV YHXB
                    xizmati xizmatlaridan foydalanishni boshlang.</h3>
                <p class="mt-3 mb-3">
                    <a href="{% url 'user:login_first' %}" class="btn btn-secondary waves-effect waves-light">
                        Kirish & A'zo bo'lish<span class="btn-label-right"><i class="mdi mdi-login"></i></span>
                    </a>

                </p>
            </div>
        </div>

    </div>
    <div class="row">

        {% for service in services %}
            <div class="col-lg-4">
                <a href="{% url 'service:service_info' service.id %}">
                    <div class="card bg-pattern service_list">
                        <div class="card-body">
                            <div class="text-center">
                                <img src="{{ service.image }}"
                                     alt="logo" class="avatar-xl mb-3">
                                <h4 class="mb-2  text-blue font-28">{{ service.title }}</h4>

                            </div>

                            <p class="font-14 text-center text-muted">
                                {{ service.desc|truncatechars:90 }}
                            </p>

                            <div class="text-center">
                                <a href="{% url 'service:service_info' service.id %}" class="btn btn-blue">Xizmatdan
                                    foydalanish</a>
                            </div>


                        </div>
                    </div> <!-- end card -->
                </a>
            </div>
        {% endfor %}


    </div>

{% endblock content %}

templates/rib/services/step_by_step.html
{% extends 'base.html' %}
{% load static %}
{% block top %}
    <link href="{% static 'assets/libs/mohithg-switchery/switchery.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/libs/multiselect/css/multi-select.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/libs/select2/css/select2.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/libs/selectize/css/selectize.bootstrap3.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css' %}" rel="stylesheet"
          type="text/css"/>
    {% include 'rib/services/part/step_by_step/css.html' %}
{% endblock top %}

{% block content %}
    <div class="row">
        <div class="col-12 info_area">
            <h2 class="text-center m-1 text-blue title_service">{{ service.title }}</h2>
            <p class="text-justify font-15">{{ service.desc }}</p>
            <div class="row">
                <div class="col-xl-12">
                    <div class="card">
                        <div class="card-body">
                            <h2 class="header-title font-22  text-center text-capitalize mb-3">{{ stepbystep.service.title }}</h2>
                            <form action="{% url 'service:save_data' %}" method="POST">
                                {% csrf_token %}


                                <input type="hidden" name="service" value="{{ object.service.pk }}">
                                <div id="progressbarwizard">
                                    <div id="bar" class="progress mb-3" style="height: 15px !important;">
                                        <div class="bar progress-bar progress-bar-striped progress-bar-animated bg-primary"></div>
                                    </div>
                                    <ul class="nav nav-pills bg-light nav-justified form-wizard-header mb-3">
                                        {% for step in stepbystep.step_with_step_by_step.all %}
                                            <li class="nav-item">
                                                <a href="#account-{{ forloop.counter }}" data-bs-toggle="tab"
                                                   data-toggle="tab"
                                                   class="nav-link rounded-0 pt-2 pb-2">
                                                    <i class="mdi {{ step.icon }} me-1"></i>
                                                    <span class="d-none d-sm-inline">{{ step.title }}</span>
                                                </a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                    <div class="tab-content b-0 mb-0 pt-0">

                                        {% for step in stepbystep.step_with_step_by_step.all %}

                                            {% include 'rib/services/part/step_by_step/accordion_step.html' %}

                                        {% endfor %}

                                        <ul class="list-inline mb-0 wizard">
                                            <li class="previous list-inline-item">
                                                <a href="javascript: void(0);" class="btn btn-secondary">Oldingi</a>
                                            </li>

                                            <li class="next list-inline-item"
                                                {% if forloop.last %}style="display:none" {% endif %}>
                                                <a href="javascript: void(0);" class="btn btn-secondary"
                                                   id="next_button">Keyingi</a>
                                            </li>


                                            <li class="list-inline-item float-end " style="mmargin-left: 15px;">
                                                <button type="submit" class="btn btn-success">Kiritish</button>
                                            </li>
                                            <li class="list-inline-item float-end">
                                                <button type="reset" class="btn btn-danger">Tozalash</button>
                                            </li>
                                        </ul>
                                    </div> <!-- tab-content -->
                                </div> <!-- end #progressbarwizard-->
                            </form>
                        </div> <!-- end card-body -->
                    </div> <!-- end card-->
                </div> <!-- end col -->
            </div>
        </div>
    </div>
{% endblock content %}

{% block bottom %}
    <script src="{% static 'assets/libs/selectize/js/standalone/selectize.min.js' %}"></script>
    <script src="{% static 'assets/libs/mohithg-switchery/switchery.min.js' %}"></script>
    <script src="{% static 'assets/libs/multiselect/js/jquery.multi-select.js' %}"></script>
    <script src="{% static 'assets/libs/select2/js/select2.min.js' %}"></script>
    <script src="{% static 'assets/libs/jquery-mockjax/jquery.mockjax.min.js' %}"></script>
    <script src="{% static 'assets/libs/devbridge-autocomplete/jquery.autocomplete.min.js' %}"></script>
    <script src="{% static 'assets/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js' %}"></script>
    <script src="{% static 'assets/libs/bootstrap-maxlength/bootstrap-maxlength.min.js' %}"></script>
    <script src="{% static 'assets/libs/twitter-bootstrap-wizard/jquery.bootstrap.wizard.min.js' %}"></script>
    <script src="{% static 'assets/js/pages/form-wizard.init.js' %}"></script>
    <!-- Init js-->
    <script src="{% static 'assets/js/pages/form-advanced.init.js' %}"></script>
    <script>
        $(document).ready(function () {
            $("#organization_div").hide()
            $("select#person_type").change(function () {
                var person_type = $(this).children("option:selected").val();
                if (person_type == 1) {
                    $("#organization_div").fadeIn()
                } else {
                    $("#organization_div").fadeOut()
                }


            });

            {% for field in stepbystep.service.service_input_field.all %}
                {{ field.js_code|safe }}
            {% endfor %}


        });

    </script>

{% endblock %}