rib/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from rib import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('service.urls')),
    path('user/', include('user.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path, include
from service.views import *


app_name = 'service'

urlpatterns = [
    path('', ServicesList.as_view(), name='services_list'),
    path('service/info/<int:pk>/', ServiceInfo.as_view(), name='service_info'),
    path('service/save-data/', SaveData.as_view(), name='save_data'),
    path('service/step-by-step/<int:pk>/', StepByStep.as_view(), name='step_by_step'),
    path('service/save-data-succes/', SaveDataSuccess.as_view(), name='save_data_success'),
    path('applications/list/', ApplicationsList.as_view(), name='applications_list'),
    path('application/detail/<int:pk>', ApplicationDetail.as_view(), name='application_detail'),
    path('get-car-data/', GetCarData.as_view(), name='get_car_data'),
]

templates/rib/application/application_detail.html
{% extends 'base.html' %}
{% load mathfilters %}
{% load service_tags %}
{% load i18n %}
{% block top %}
    <style>
        .wrp {
            background: #fff;
        }
    </style>
{% endblock top %}
{% block content %}
    <div class="row wrp p-2 mb-1">
        <h2 class="text-center">{% trans "Ariza raqami: " %}#{{ application.pk }} | Xizmat
            turi: {{ application.service.title }}</h2>


        <div class="row">
            <div class="col-xl-12">
                {% for step in steps %}
                    {{ step.step }}
                    <div id="accordion" class="mb-3">
                    <div class="card mb-1">
                        <a class="text-dark" data-bs-toggle="collapse" href="#collapse{{ step.pk }}"
                           aria-expanded="true">
                            <div class="card-header" id="headingOne">
                                <h5 class="m-0">


                                    <h3><i class="mdi {{ step.icon }} me-1 text-secondary"></i>{{ step.title }}</h3>

                                </h5>
                            </div>
                        </a>

                        <div id="collapse{{ step.pk }}" class="collapse show" aria-labelledby="headingOne"
                             data-bs-parent="#accordion">
                            <div class="card-body">
                                {{ step }}
                            </div>
                        </div>

                    </div>

                {% endfor %}
                <div class="card mb-1">
                    <a class="text-dark" data-bs-toggle="collapse" href="#collapseDuty"
                       aria-expanded="true">
                        <div class="card-header" id="headingOne">
                            <h5 class="m-0">
                                <h3><i class="mdi {{ step.icon }} me-1 text-secondary"></i>Davlat boji</h3>
                            </h5>
                        </div>
                    </a>
                    <div id="collapseDuty" class="collapse show" aria-labelledby="headingOne"
                         data-bs-parent="#accordion">
                        <div class="card-body">
                            <table class="table table-striped table-responsive">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Davlat boji</th>
                                    <th>Foizi</th>
                                    <th>Summasi</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for state_duty in  application.service.state_duty_with_service.all %}
                                    <tr>
                                        {% for percent in state_duty.state_duty_percent_with_state_duty.all %}

                                            {% if percent.state_duty.key  == 'road_fund' %}
                                                {% if percent.made_year_start <= age and   percent.made_year_stop >= age %}
                                                    <td>#</td>
                                                    <td>{{ percent.state_duty }}</td>
                                                    <td>{{ percent.percent }} %</td>
                                                    <td>{% get_state_duty_sum  MINIMUM_BASE_WAGE percent.percent%}</td>
                                                {% endif %}
                                            {% else %}
                                                <td>#</td>
                                                <td>{{ percent.state_duty }}</td>
                                                <td>{{ percent.percent }} %</td>

                                                <td id="">{% get_state_duty_sum  MINIMUM_BASE_WAGE percent.percent %}

                                                {{ sum }}</td>
                                            {% endif %}
                                        {% endfor %}
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                </div> <!-- end col -->


            </div> <!-- end row -->

        </div>
{% endblock content %}

templates/rib/application/applications_list.html
{% extends 'base.html' %}
{% load static i18n service_tags %}
{% block top %}
    <!-- third party css -->
    <link href="{% static 'assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet"
          type="text/css"/>
    <link href="{% static 'assets/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}"
          rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet"
          type="text/css"/>
    <link href="{% static 'assets/libs/datatables.net-select-bs4/css//select.bootstrap4.min.css' %}" rel="stylesheet"
          type="text/css"/>
    <!-- third party css end -->
{% endblock top %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Basic Data Table</h4>

                    <table id="example1" class="table dt-responsive nowrap w-100">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Xizmat turi</th>
                            <th>Avtomobil</th>
                            <th>Arizachi</th>
                            <th>Kiritilgan vaqti</th>
                            <th>Holat</th>

                        </tr>
                        </thead>


                        <tbody>

                        {#                        {% for application in application_list %}#}
                        {#                            <tr>#}
                        {#                                <td>{{ forloop.counter }}</td>#}
                        {#                                <td>{{ application.service }}</td>#}
                        {#                                <td>#}
                        {#                                    {% if application.organization %}#}
                        {#                                        {{ application.organization }}#}
                        {#                                    {% else %}#}
                        {#                                        {{ application.created_user }}#}
                        {#                                    {% endif %}#}
                        {#                                </td>#}
                        {#                                <td>{{ application.created_date|date:"SHORT_DATETIME_FORMAT" }}</td>#}
                        {##}
                        {#                                <td class="footable-visible footable-last-column" style="">#}
                        {#                                    {% if application.process == '1' %}#}
                        {#                                        <span class="badge label-table bg-warning">Jarayonda</span>#}
                        {##}
                        {#                                    {% elif application.process == '2' %}#}
                        {#                                        <span class="badge label-table bg-success">Qabul qilingan</span>#}
                        {##}
                        {#                                    {% elif application.process == '3' %}#}
                        {#                                        <span class="badge label-table bg-danger">Rad etilgan</span>#}
                        {#                                    {% endif %}#}
                        {#                                </td>#}
                        {#                            </tr>#}
                        {#                        {% endfor %}#}

                        </tbody>
                    </table>

                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->

    </div>

{% endblock content %}

{% block bottom %}
    <!-- third party js -->
    <script src="{% static 'assets/libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-select/js/dataTables.select.min.js' %}"></script>
    <script src="{% static 'assets/libs/pdfmake/build/pdfmake.min.js' %}"></script>
    <script src="{% static 'assets/libs/pdfmake/build/vfs_fonts.js' %}"></script>
    <script src="{% static 'assets/js/pages/datatables.init.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <!-- third party js ends -->
    <script type="text/javascript" class="init">
        $(document).ready(function () {
            var
                csrftoken = getCookie('csrftoken'),
                url = null
            $.ajaxSetup({
                beforeSend: function (xhr) {
                    xhr.setRequestHeader('X-CSRFToken', csrftoken)
                },
                error: function (response) {
                    if (response.status === 401) {
                        alert('Token Invalid')
                    }
                }
            })

            $("#example1").DataTable({
                "serverSide": true,
                "processing": true,
                'autoWidth': false,
                "orderCellsTop": true,
                language: {
                    search: "_INPUT_",
                    searchPlaceholder: "{% trans 'Qidiruv...' %}",
                    "emptyTable": `{% trans "Ma'lumot topilmadi!" %}`,
                    {#"info": "Ko'rsatilgan _END_ dan _START_. Jami: _TOTAL_ ta ma'lumot",#}
                    "info": `{% trans "Jami: _TOTAL_ ta ariza" %}`,
                    "infoEmpty": `{% trans "Jami: _TOTAL_ ta ariza" %}`,
                    "infoFiltered": "(filtered from _MAX_ total entries)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "_MENU_",
                    "loadingRecords": "{% trans 'Yuklanmoqda...' %}",
                    "processing": '{% trans "Qayta ishlanmoqda" %}',
                    "zeroRecords": `{% trans "Ma'lumot topilmadi!" %}`,
                    "paginate": {
                        "first": "{% trans 'Birinchi' %}",
                        "last": "{% trans 'Oxirgi' %}",
                        "next": "{% trans 'Keyingi' %}",
                        "previous": "{% trans 'Oldingi' %}"
                    },
                    "aria": {
                        "sortAscending": `{% trans ": o'sish tartibi faollashtirildi" %}`,
                        "sortDescending": `{% trans ": kamayish tartibi faollashtirildi" %}`,
                    }
                },
                "ajax": function (data, callback, settings) {
                    console.log(data)
                    $.ajax({
                        url: '{% url "service:applications_list" %}',
                        type: 'GET',
                        dataType: "json",
                        cache: false,
                        contentType: "application/json; charset=utf-8",
                        data: {
                            limit: data.length,
                            start: data.start,
                            q: data.search.value,
                            order_by: data.columns[data.order[0].column].data.replace(/\./g, "__"),
                        }
                    }).then(function (res) {
                        console.log(res, 158)
                        callback({
                            recordsTotal: res.length,
                            recordsFiltered: res.length,
                            data: res.objects
                        });
                    });
                },
                "columns": [
                    {"data": "id"},
                    {"data": "service"},
                    {
                        "render": function (data, type, full, meta) {

                            $.ajax({
                                url: "{% url 'service:get_car_data' %}",
                                type: "POST",
                                data: {
                                    'app_id': full.id
                                },
                                success: function (res) {
                                    console.log(res)
                                    return res
                                },
                                error: function () {
                                    console.log(full.id + ' car not found')
                                    return ''
                                }
                            })

                        }
                    },
                    {"data": "created_user"},
                    {"data": "created_date"},
                    {
                        "data": "process",
                        render: function (data, type, row) {
                            if (row.process === '1') {
                                return '<span class="badge label-table bg-warning">Jarayonda</span>'
                            } else if (row.process === '2') {
                                return '<span class="badge label-table bg-success">Qabul qilingan</span>'
                            } else if (row.process === '3') {
                                return '<span class="badge label-table bg-danger">Rad etilgan</span>'
                            }
                        }

                    },
                ]
            })


        })
    </script>
{% endblock bottom %}